#!/bin/sh

set -e

# For local debugging
if [ -n "$LOCAL_LAYERS_DIR" ]; then
  LAYERS_DIR=$LOCAL_LAYERS_DIR
  DEPS_CLASSPATH_FILE="$LAYERS_DIR/deps-local-classpath"
  RUNTIME_CLASSPATH_FILE="$LAYERS_DIR/runtime-local-classpath"
else
  LAYERS_DIR=/opt
  DEPS_CLASSPATH_FILE="$LAYERS_DIR/deps-classpath"
  RUNTIME_CLASSPATH_FILE="$LAYERS_DIR/runtime-classpath"
fi

CLASSPATH=$LAMBDA_TASK_ROOT
if [ -e $DEPS_CLASSPATH_FILE ]; then
  CLASSPATH="$CLASSPATH:`cat $DEPS_CLASSPATH_FILE`"
fi
if [ -e $RUNTIME_CLASSPATH_FILE ]; then
  CLASSPATH="$CLASSPATH:`cat $RUNTIME_CLASSPATH_FILE`"
fi

export GITLIBS=$LAYERS_DIR/gitlibs

echo "Starting JRE:"
echo "$LAYERS_DIR/bin/java -cp $CLASSPATH clojure.main $LAYERS_DIR/bootstrap.clj"

$LAYERS_DIR/bin/java -cp $CLASSPATH clojure.main $LAYERS_DIR/bootstrap.clj
